### ISSUE TITLE
Clarify usage of this vs newer(?) modules

### ISSUE THREAD

**Issue by xavdid** [heroku/heroku-cli-util#111]
Hi there!

I was reading through some [docs](https://devcenter.heroku.com/articles/developing-cli-plugins) and noticed they've changed a lot since I wrote my plugin last year. The biggest difference is the introduction of `cli-engine-heroku`, heavily featured in the intro article. Looks pretty slick!

I'd love to see some documentation on future plans for the modules (is `cli-util` getting deprecated in favor of `cli-engine`?). For instance, if I was starting a new module today, which should I use? Is it worth updating an existing plugin with the new modules? If it's not right now (docs not ready, whatever), is there a planned point where that's the recommended action?

Related, the `in the code` link in [this](https://devcenter.heroku.com/articles/developing-cli-plugins#warnings-and-errors) section is 404.

**Comment by jdxcode** [comment]
so yeah, that is the plane to deprecate `cli-util` in favor of `cli-engine`. We still have some documentation work to complete this quarter to fully migrate our documentation over. For now, you can continue to use either one really, just because it's deprecated doesn't mean it will stop working. We will not be converting our internal code over to use `cli-util` either, just writing new code with it.
