### ISSUE TITLE
When two factor is requested, would it be possible to preauth globally?

### ISSUE THREAD

**Issue by ransombriggs** [heroku/heroku-cli-util#75]
@dickeyxxx @mikehale pointed out that when he was doing `heroku config` on a 2fa app, it would prompt over an over, until he ran `heroku apps:info` after which `heroku config` stopped prompting.  He was wondering the difference and it comes down to preAuth being set in apps:info.  Besides performance, is there a reason that preAuth behavior is not the default.  Having this behavior appear & disappear does seem inconsistent.

https://github.com/heroku/heroku-cli-util/blob/4c1a8f903462b21e81d8915e9f5a8ce363c7646d/lib/command.js#L102

**Comment by dickeyxxx** [comment]
Well originally we didn't want to ever do preauth. We wanted to have every command have a single API command so it wasn't necessary and API considered anything else a bug. I don't think that's the current opinion though. I don't really like the preauth strategy. I think it gives a strange side effect to using the CLI against a paranoid app. However, I don't know a better way to do it and a strange side effect is probably better being consistent rather than sometimes.

**Comment by mikehale** [comment]
If it helps the behavior I would like to see is having my 2fa cached for some period of time. Whether that is via preauth or some other mechanism is fine by me. I just really don't want to have to enter my yubikey 5 times in a row when running a script or exploring an app.

**Comment by dickeyxxx** [comment]
that's another option, we could just emit to stderr everytime we 2fa. I don't have a strong preference here.

**Comment by mikehale** [comment]
how does emitting to stderr cause 2fa to be cached?

**Comment by dickeyxxx** [comment]
I'm just saying we could emit a message saying we're preauthing

**Comment by mikehale** [comment]
Gotcha, that would certainly make things clearer, especially if we include the amount of time the pre-auth will be valid for.

**Comment by ransombriggs** [comment]
The behavior around preauth has changed and now it is defaults to true when a two factor header is returned, closing.
